version: '3.1'

services:

  db:
    image: postgres:9.6
    restart: always
    environment:
      # POSTGRES_USER: user
      # POSTGRES_PASSWORD: password
      POSTGRES_DB: gsp
    ports:
      - 5432:5432

