-------------------------------
-- Giapi status apply for GHOST
-------------------------------

INSERT INTO e_giapi_status_apply(id, instrument_id, type, status_item, apply_item)
VALUES
	('FiberAgitator1', 'Ghost', 'Int', 'ghost:sad:cc:slu:fa1.active', 'ghost:cc:slu:fa1.type'),
	('FiberAgitator2', 'Ghost', 'Int', 'ghost:sad:cc:slu:fa2.active', 'ghost:cc:slu:fa2.type'),
	('RedExposureTime', 'Ghost', 'Double', 'ghost:sad:dc:red.exposedRQ', 'ghost:dc:red.duration'),
	('RedExposureCount', 'Ghost', 'Int', 'ghost:sad:dc:red.repeat', 'ghost:dc:red.repeat'),
	('RedExposureBinningRcf', 'Ghost', 'Int', 'ghost:sad:dc:red:binx', 'ghost:dc:red.rcf'),
	('RedExposureBinningCcf', 'Ghost', 'Int', 'ghost:sad:dc:red:biny', 'ghost:dc:red.ccf'),
	('BlueExposureTime', 'Ghost', 'Double', 'ghost:sad:dc:blue.exposedRQ', 'ghost:dc:blue.duration'),
	('BlueExposureCount', 'Ghost', 'Int', 'ghost:sad:dc:blue.repeat:GhostBlue.repeat', 'ghost:dc:blue.repeat'),
	('BlueExposureBinningRcf', 'Ghost', 'Int', 'ghost:sad:dc:blue:binx', 'ghost:dc:blue.rcf'),
	('BlueExposureBinningCcf', 'Ghost', 'Int', 'ghost:sad:dc:blue:biny', 'ghost:dc:blue.ccf'),
	('IFU1Bundle', 'Ghost', 'Int', 'ghost:sad:cc:cu:ifu1.bundle', 'ghost:cc:cu:ifu1.bundle'),
	('IFU2Bundle', 'Ghost', 'Int', 'ghost:sad:cc:cu:ifu2.bundle', 'ghost:cc:cu:ifu2.bundle'),
	('SRIFU1CoordsRADeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu1.ra', 'ghost:cc:cu:ifu1.ra'),
	('SRIFU1CoordsDecDeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu1.dec', 'ghost:cc:cu:ifu1.dec'),
	('SRIFU2CoordsRADeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu2.ra', 'ghost:cc:cu:ifu2.ra'),
	('SRIFU2CoordsDecDeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu2.dec', 'ghost:cc:cu:ifu2.dec'),
	('HRIFU1CoordsRADeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu1.ra', 'ghost:cc:cu:ifu1.ra'),
	('HRIFU1CoordsDecDeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu1.dec', 'ghost:cc:cu:ifu1.dec'),
	('HRIFU2CoordsRADeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu2.ra', 'ghost:cc:cu:ifu2.ra'),
	('HRIFU2CoordsDecDeg', 'Ghost', 'Double', 'ghost:sad:cc:cu:ifu2.dec', 'ghost:cc:cu:ifu2.dec'),
	('UserTarget0Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target0_name', 'ghost:cc:cu:targets.target0_name'),
	('UserTarget0CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target0_ra', 'ghost:cc:cu:targets.target0_ra'),
	('UserTarget0CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target0_dec', 'ghost:cc:cu:targets.target0_dec'),
	('UserTarget1Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target1_name', 'ghost:cc:cu:targets.target1_name'),
	('UserTarget1CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target1_ra', 'ghost:cc:cu:targets.target1_ra'),
	('UserTarget1CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target1_dec', 'ghost:cc:cu:targets.target1_dec'),
	('UserTarget2Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target2_name', 'ghost:cc:cu:targets.target2_name'),
	('UserTarget2CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target2_ra', 'ghost:cc:cu:targets.target2_ra'),
	('UserTarget2CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target2_dec', 'ghost:cc:cu:targets.target2_dec'),
	('UserTarget3Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target3_name', 'ghost:cc:cu:targets.target3_name'),
	('UserTarget3CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target3_ra', 'ghost:cc:cu:targets.target3_ra'),
	('UserTarget3CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target3_dec', 'ghost:cc:cu:targets.target3_dec'),
	('UserTarget4Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target4_name', 'ghost:cc:cu:targets.target4_name'),
	('UserTarget4CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target4_ra', 'ghost:cc:cu:targets.target4_ra'),
	('UserTarget4CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target4_dec', 'ghost:cc:cu:targets.target4_dec'),
	('UserTarget5Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target5_name', 'ghost:cc:cu:targets.target5_name'),
	('UserTarget5CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target5_ra', 'ghost:cc:cu:targets.target5_ra'),
	('UserTarget5CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target5_dec', 'ghost:cc:cu:targets.target5_dec'),
	('UserTarget6Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target6_name', 'ghost:cc:cu:targets.target6_name'),
	('UserTarget6CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target6_ra', 'ghost:cc:cu:targets.target6_ra'),
	('UserTarget6CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target6_dec', 'ghost:cc:cu:targets.target6_dec'),
	('UserTarget7Name', 'Ghost', 'String', 'ghost:cc:cu:targets.target7_name', 'ghost:cc:cu:targets.target7_name'),
	('UserTarget7CoordsRADeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target7_ra', 'ghost:cc:cu:targets.target7_ra'),
	('UserTarget7CoordsDecDeg', 'Ghost', 'Double', 'ghost:cc:cu:targets.target7_dec', 'ghost:cc:cu:targets.target7_dec'),
	('UserTargetCount', 'Ghost', 'Int', 'ghost:cc:cu:targets.targets.n_targets', 'ghost:cc:cu:targets.targets.n_targets'),
	('AgEnableGuide', 'Ghost', 'Boolean', 'ghost:dc:ag.enable_guide', 'ghost:dc:ag.enable_guide'),
	('AgFiberMode1', 'Ghost', 'Int', 'ghost:dc:ag.pos1_mode', 'ghost:dc:ag.pos1_mode'),
	('AgFiberMode2', 'Ghost', 'Int', 'ghost:dc:ag.pos2_mode', 'ghost:dc:ag.pos2_mode'),
	('UserTargetCount', 'Ghost', 'Int', 'ghost:cc:cu:targets.targets.n_targets', 'ghost:cc:cu:targets.targets.n_targets');
