name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v2
        with:
          java-version: 1.8
      - name: Run compile/test
        run: csbt headerCheck +compile +test
