name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v2
        with:
          java-version: 1.8
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Run compile
        run: csbt headerCheck +compile +test
