name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK 14
        uses: olafurpg/setup-scala@v7
        with:
          java-version: adoptjdk@14
      - name: Run compile
        run: csbt headerCheck +compile +test rebuildEnums
